### ISSUE TITLE
Importing haze library crashes on runtime when m3 CircularProgressIndicator starts spinning

### ISSUE THREAD

**Issue by Vissnor** [chrisbanes/haze#120]
## Information

  - Haze version: 0.5.0
  - Platform: Android, Jetpack Compose
  - compose-bom = "2023.10.01"
  - material = "1.10.0" (also tested on 1.11.0)

## Actual Behavior
When adding the haze dependency (without using it anywhere) and running my app with a CircularProgressIndicator being shown it crashes. After removing the dependency it doesn't crash. Tested it multiple times and same result.

## Steps to Reproduce the Problem
java.lang.NoSuchMethodError: No virtual method at(Ljava/lang/Object;I)
Landroidx/compose/animation/core/KeyframesSpec$KeyframeEntity; in class
Landroidx/compose/animation/core/KeyframesSpec$KeyframesSpecConfig; or its super classes (declaration of 'androidx.compose.animation.core.KeyframesSpec$KeyframesSpecConfig' appears in /data/app/~~i_o5gVWscTtLwqcpHsHQ4Q==/
at androidx.compose.material3.ProgressIndicatorKt$CircularProgressIndicator$endAngle$1.invoke(ProgressIndicator.kt:371)
at androidx.compose.material3.ProgressIndicatorKt$CircularProgressIndicator$endAngle$1.invoke(ProgressIndicator.kt:369)

**Comment by chrisbanes** [comment]
Upstream bug: https://github.com/JetBrains/compose-multiplatform/issues/4157

Nothing we can do about this.
