### ISSUE TITLE
exception nativePtr is null

### ISSUE THREAD

**Issue by crowforkotlin** [chrisbanes/haze#352]
- Platform Android
- Project type : Kotlin Multiplatform
- Androrid Version 14 API 34
- SystemOs Facotry: XiaoMi HyperOs
- haze-version = "0.7.3"
- compose-plugin = "1.7.0-rc01"
- kotlin = "2.0.20"
```
FATAL EXCEPTION: main
                 Process: com.crow.mordecaix, PID: 6418
                 java.lang.IllegalArgumentException: nativePtr is null
                 	at libcore.util.NativeAllocationRegistry.registerNativeAllocation(NativeAllocationRegistry.java:264)
                 	at android.graphics.RenderEffect.<init>(RenderEffect.java:314)
                 	at android.graphics.RenderEffect.createBlurEffect(RenderEffect.java:117)
                 	at dev.chrisbanes.haze.RenderNodeImpl.updateRenderEffect(AndroidHazeNode.kt:427)
                 	at dev.chrisbanes.haze.RenderNodeImpl.update(AndroidHazeNode.kt:420)
                 	at dev.chrisbanes.haze.RenderNodeImpl.draw(AndroidHazeNode.kt:284)
                 	at dev.chrisbanes.haze.AndroidHazeNode.draw(AndroidHazeNode.kt:140)
                 	at androidx.compose.ui.node.LayoutNodeDrawScope.drawDirect-eZhPAX0$ui_release(LayoutNodeDrawScope.kt:110)
                 	at androidx.compose.ui.node.LayoutNodeDrawScope.draw-eZhPAX0$ui_release(LayoutNodeDrawScope.kt:89)
                 	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:450)
                 	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:439)
                 	at androidx.compose.ui.node.LayoutNode.draw$ui_release(LayoutNode.kt:999)
                 	at androidx.compose.ui.node.InnerNodeCoordinator.performDraw(InnerNodeCoordinator.kt:196)
                 	at androidx.compose.ui.node.LayoutNodeDrawScope.drawContent(LayoutNodeDrawScope.kt:68)
                 	at androidx.compose.foundation.BackgroundNode.draw(Background.kt:163)
                 	at androidx.compose.ui.node.LayoutNodeDrawScope.drawDirect-eZhPAX0$ui_release(LayoutNodeDrawScope.kt:110)
                 	at androidx.compose.ui.node.LayoutNodeDrawScope.draw-eZhPAX0$ui_release(LayoutNodeDrawScope.kt:89)
                 	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:450)
                 	at androidx.compose.ui.node.NodeCoordinator.access$drawContainedDrawModifiers(NodeCoordinator.kt:58)
                 	at androidx.compose.ui.node.NodeCoordinator$drawBlock$1$1.invoke(NodeCoordinator.kt:469)
                 	at androidx.compose.ui.node.NodeCoordinator$drawBlock$1$1.invoke(NodeCoordinator.kt:468)
                 	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2441)
                 	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:502)
                 	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:258)
                 	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:133)
                 	at androidx.compose.ui.node.NodeCoordinator$drawBlock$1.invoke(NodeCoordinator.kt:468)
                 	at androidx.compose.ui.node.NodeCoordinator$drawBlock$1.invoke(NodeCoordinator.kt:466)
                 	at androidx.compose.ui.platform.GraphicsLayerOwnerLayer$recordLambda$1.invoke(GraphicsLayerOwnerLayer.android.kt:291)
                 	at androidx.compose.ui.platform.GraphicsLayerOwnerLayer$recordLambda$1.invoke(GraphicsLayerOwnerLayer.android.kt:289)
                 	at androidx.compose.ui.graphics.layer.GraphicsLayerV29.record(GraphicsLayerV29.android.kt:245)
                 	at androidx.compose.ui.graphics.layer.GraphicsLayer.recordInternal(AndroidGraphicsLayer.android.kt:430)
                 	at androidx.compose.ui.graphics.layer.GraphicsLayer.record-mL-hObY(AndroidGraphicsLayer.android.kt:423)
                 	at androidx.compose.ui.platform.GraphicsLayerOwnerLayer.updateDisplayList(GraphicsLayerOwnerLayer.android.kt:284)
                 	at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(AndroidComposeView.android.kt:1572)
                 	at android.view.View.draw(View.java:24726)
                 	at android.view.View.updateDisplayListIfDirty(View.java:23554)
                 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4607)
                 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4580)
                 	at android.view.View.updateDisplayListIfDirty(View.java:23488)
                 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4607)
                 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4580)
                 	at android.view.View.updateDisplayListIfDirty(View.java:23488)
                 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4607)
                 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4580)
                 	at android.view.View.updateDisplayListIfDirty(View.java:23488)
13:51:38.013  E  	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4607)
                 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4580)
                 	at android.view.View.updateDisplayListIfDirty(View.java:23488)
                 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:726)
                 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:735)
                 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:845)
                 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:5541)
                 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5220)
                 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4352)
                 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2933)
                 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10235)
                 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1634)
                 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1643)
                 	at android.view.Choreographer.doCallbacks(Choreographer.java:1172)
                 	at android.view.Choreographer.doFrame(Choreographer.java:1076)
                 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1607)
                 	at android.os.Handler.handleCallback(Handler.java:958)
                 	at android.os.Handler.dispatchMessage(Handler.java:99)
                 	at android.os.Looper.loopOnce(Looper.java:224)
                 	at android.os.Looper.loop(Looper.java:318)
                 	at android.app.ActivityThread.main(ActivityThread.java:8772)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
```

```
@OptIn(ExperimentalResourceApi::class)
@Composable
fun SourceScreen() {
    var hazeRadius by remember { mutableStateOf(2.dp) }
    val sources = getKoin().get<List<SourceModel>>()
    LaunchedEffect(Unit) {
        while (true) {
            delay(2000)
            hazeRadius = if (hazeRadius.value < 2) {
                (hazeRadius.value + 0.2).dp
            } else {
                0.dp
            }
        }
    }
    LazyColumn(modifier = Modifier.fillMaxSize()) {
        items(sources.size) {
            val hazeState = remember { HazeState() }
            Box(
                modifier = Modifier
                    .padding(10.dp)
                    .fillMaxSize()
                    .border(1.dp, Color.LightGray.copy(alpha = 0.5f), RoundedCornerShape(7.5.dp))
                    .shadow(1.dp, RoundedCornerShape(7.5.dp))
                    .background(MaterialTheme.colorScheme.primary)
                    .hazeChild(hazeState),
            ) {
                Row(
                    modifier = Modifier.haze(
                        hazeState,
                        HazeDefaults.style(noiseFactor = 0f, blurRadius = hazeRadius)
                    )
                ) {
                    Icon(
                        imageVector = Icons.Rounded.Create,
                        contentDescription = null,
                        modifier = Modifier.padding(10.dp)
                    )
                    Text(
                        text = sources[it].mName,
                        style = MaterialTheme.typography.bodyLarge.copy(fontWeight = FontWeight.Medium),
                        modifier = Modifier.padding(10.dp)

                    )
                }
            }
        }
    }
}
```

After two seconds of delay, the Android machine crashes directly, and the desktop is normal

**Comment by chrisbanes** [comment]
Please try with the latest 0.9.0 beta instead, as it’s basically a full rewrite.

**Comment by crowforkotlin** [comment]
> Please try with the latest 0.9.0 beta instead, as it’s basically a full rewrite.请尝试使用最新的 0.9.0 beta 版本，因为它基本上是完全重写的。

Thanks, it's been resolved
