### ISSUE TITLE
Crash: java.lang.IllegalArgumentException: backgroundColor not specified. Please provide a color.

### ISSUE THREAD

**Issue by sudheeshmohan47** [chrisbanes/haze#395]
## Information

  - Haze version: 1.0.0
  - Platform: Android
  - Platform version: Android 14

## Behavior
I am experiencing crash 
` java.lang.IllegalArgumentException: backgroundColor not specified. Please provide a color.
`when using hazeChild()

This started happening after updating to new version 1.0.0. 
As the latest change([haze/pull/265](https://github.com/chrisbanes/haze/pull/265)) in new version we need to specify background color when using hazeChild. But where do we specify this? 

As per this sample ([ScaffoldSample.kt](https://github.com/chrisbanes/haze/blob/main/sample/shared/src/commonMain/kotlin/dev/chrisbanes/haze/sample/ScaffoldSample.kt)) dev.chrisbanes.haze.materials.HazeMaterials is used to set the style. But HazeMaterials is not showing up with v1.0.0.

Could you please look into this issue?

Crash: 

```
java.lang.IllegalArgumentException: backgroundColor not specified. Please provide a color.
                                                                                                    	at dev.chrisbanes.haze.HazeChildNode.drawEffectWithGraphicsLayer$lambda$26(HazeChildNode.kt:296)
                                                                                                    	at dev.chrisbanes.haze.HazeChildNode.$r8$lambda$r1HDnNv10MaXz_bu2cEaBm19yyY(Unknown Source:0)
                                                                                                    	at dev.chrisbanes.haze.HazeChildNode$$ExternalSyntheticLambda12.invoke(D8$$SyntheticClass:0)
                                                                                                    	at androidx.compose.ui.graphics.drawscope.DrawScope$record$1.invoke(DrawScope.kt:1077)
                                                                                                    	at androidx.compose.ui.graphics.drawscope.DrawScope$record$1.invoke(DrawScope.kt:941)
                                                                                                    	at androidx.compose.ui.graphics.layer.GraphicsLayer$clipDrawBlock$1.invoke(AndroidGraphicsLayer.android.kt:71)
                                                                                                    	at androidx.compose.ui.graphics.layer.GraphicsLayer$clipDrawBlock$1.invoke(AndroidGraphicsLayer.android.kt:66)
                                                                                                    	at androidx.compose.ui.graphics.layer.GraphicsLayerV29.record(GraphicsLayerV29.android.kt:251)
                                                                                                    	at androidx.compose.ui.graphics.layer.GraphicsLayer.recordInternal(AndroidGraphicsLayer.android.kt:436)
                                                                                                    	at androidx.compose.ui.graphics.layer.GraphicsLayer.record-mL-hObY(AndroidGraphicsLayer.android.kt:429)
                                                                                                    	at androidx.compose.ui.graphics.drawscope.DrawScope.record-JVtK1S4(DrawScope.kt:941)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeDrawScope.record-JVtK1S4(Unknown Source:2)
                                                                                                    	at dev.chrisbanes.haze.HazeChildNode.drawEffectWithGraphicsLayer(HazeChildNode.kt:294)
                                                                                                    	at dev.chrisbanes.haze.HazeChildNode.draw(HazeChildNode.kt:256)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeDrawScope.drawDirect-eZhPAX0$ui_release(LayoutNodeDrawScope.kt:110)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeDrawScope.draw-eZhPAX0$ui_release(LayoutNodeDrawScope.kt:89)
                                                                                                    	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:450)
                                                                                                    	at androidx.compose.ui.node.NodeCoordinator.access$drawContainedDrawModifiers(NodeCoordinator.kt:58)
                                                                                                    	at androidx.compose.ui.node.NodeCoordinator$drawBlock$1$1.invoke(NodeCoordinator.kt:469)
                                                                                                    	at androidx.compose.ui.node.NodeCoordinator$drawBlock$1$1.invoke(NodeCoordinator.kt:468)
                                                                                                    	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:503)
                                                                                                    	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:502)
                                                                                                    	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:258)
                                                                                                    	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:133)
                                                                                                    	at androidx.compose.ui.node.NodeCoordinator$drawBlock$1.invoke(NodeCoordinator.kt:468)
                                                                                                    	at androidx.compose.ui.node.NodeCoordinator$drawBlock$1.invoke(NodeCoordinator.kt:466)
                                                                                                    	at androidx.compose.ui.platform.GraphicsLayerOwnerLayer$recordLambda$1.invoke(GraphicsLayerOwnerLayer.android.kt:291)
                                                                                                    	at androidx.compose.ui.platform.GraphicsLayerOwnerLayer$recordLambda$1.invoke(GraphicsLayerOwnerLayer.android.kt:289)
                                                                                                    	at androidx.compose.ui.graphics.layer.GraphicsLayer$clipDrawBlock$1.invoke(AndroidGraphicsLayer.android.kt:71)
                                                                                                    	at androidx.compose.ui.graphics.layer.GraphicsLayer$clipDrawBlock$1.invoke(AndroidGraphicsLayer.android.kt:66)
                                                                                                    	at androidx.compose.ui.graphics.layer.GraphicsLayerV29.record(GraphicsLayerV29.android.kt:251)
                                                                                                    	at androidx.compose.ui.graphics.layer.GraphicsLayer.recordInternal(AndroidGraphicsLayer.android.kt:436)
                                                                                                    	at androidx.compose.ui.graphics.layer.GraphicsLayer.record-mL-hObY(AndroidGraphicsLayer.android.kt:429)
                                                                                                    	at androidx.compose.ui.platform.GraphicsLayerOwnerLayer.updateDisplayList(GraphicsLayerOwnerLayer.android.kt:284)
                                                                                                    	at androidx.compose.ui.platform.GraphicsLayerOwnerLayer.drawLayer(GraphicsLayerOwnerLayer.android.kt:229)
                                                                                                    	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:434)
                                                                                                    	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierNodeCoordinator.kt:280)
                                                                                                    	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:447)
                                                                                                    	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:439)
```

My code:

```
@Composable
fun HomeItemImageSection(
    home: Home,
    distance: String,
    modifier: Modifier = Modifier,
    onAction: (SearchAction) -> Unit
) {
    val hazeState = remember { HazeState() }

    Box(
        modifier = modifier
            .clip(RoundedCornerShape(Spacing.MEDIUM.dp()))
            .fillMaxSize()
    ) {
        AsyncImage(
            modifier = Modifier
                .fillMaxSize()
                .haze(state = hazeState),
            model = ImageRequest.Builder(LocalContext.current)
                .data(home.imageUrl.ifEmpty { R.drawable.placeholder_home })
                .crossfade(true)
                .scale(Scale.FIT)
                .error(R.drawable.placeholder_home)
                .build(),
            placeholder = painterResource(R.drawable.placeholder_home),
            contentDescription = "",
            contentScale = ContentScale.Crop
        )

        if (home.listItemType == ListItemType.HOME_ITEM.name) {
            HomeItemOverlayElements(
                modifier = Modifier.padding(Spacing.SMALL.dp()),
                home = home,
                distance = distance,
                onAction = onAction,
                hazeState = hazeState
            )
        }
    }
}

@Composable
fun HomeItemOverlayElements(
    home: Home,
    distance: String,
    onAction: (SearchAction) -> Unit,
    hazeState: HazeState,
    modifier: Modifier = Modifier,
) {
    Box(
        modifier = modifier
            .fillMaxSize()
            .padding(Spacing.SMALL.dp())
    ) {
        Column(modifier = Modifier.align(Alignment.BottomStart)) {
            // Other items...
            
            Row(
                modifier = Modifier.fillMaxWidth(),
                verticalAlignment = Alignment.CenterVertically
            ) {
                Text(
                    text = home.place,
                    style = MaterialTheme.typography.labelMedium,
                    fontFamily = InterFontFamily,
                    fontWeight = FontWeight.Normal,
                    color = Color.White,
                    modifier = Modifier.weight(1f),
                    overflow = TextOverflow.Ellipsis,
                    maxLines = 1
                )
                Spacer(modifier = Modifier.width(Spacing.SMALL.dp()))
                Row(
                    modifier = Modifier
                        .clip(RoundedCornerShape(Spacing.LARGE.dp()))
                        .hazeChild(
                            state = hazeState
                        )
                        .padding(
                            horizontal = Spacing.SMALL.dp(),
                            vertical = Spacing.EXTRASMALL.dp()
                        )
                ) {
                    Icon(
                        imageVector = ImageVector.vectorResource(id = R.drawable.ic_location_white),
                        contentDescription = "Location",
                        modifier = Modifier.size(Spacing.MEDIUM.dp()),
                        tint = Color.White
                    )
                    Spacer(modifier = Modifier.width(Spacing.EXTRASMALL.dp()))
                    Text(
                        text = distance,
                        style = MaterialTheme.typography.labelSmall,
                        fontFamily = InterFontFamily,
                        fontWeight = FontWeight.Bold,
                        color = Color.White
                    )
                }
            }
        }
    }
}

```
But if we give 

```
.hazeChild(
                            state = hazeState
                        ){
                            backgroundColor = Color.Black
                        }
```
 I tried setting the background for parent and haze child composable but crash still happens. But the crash wont happen but the blur effect wont be there, just a transparent background.

**Comment by chrisbanes** [comment]
See here: https://chrisbanes.github.io/haze/migrating-1.0/#haze-no-longer-clips-background-content

**Comment by sosauce** [comment]
This is my full code if needed :

```
    val hazeState = remember { HazeState() }


    Box(
        modifier = Modifier
            .fillMaxSize(),
    ) {
        LazyVerticalGrid(
            columns = GridCells.Fixed(4),
            modifier = Modifier
                .fillMaxSize()
                .hazeSource(hazeState)
        ) { ... }
                    TopAppBar(
                colors = TopAppBarDefaults.largeTopAppBarColors(Color.Transparent),
                modifier = Modifier
                    .hazeEffect(state = hazeState) {
                        backgroundColor = surface
                    }
                    .fillMaxWidth(),
                title = {
                    CuteText(albumName)
                }
            )
   }
```

**Comment by chrisbanes** [comment]
@sosauce your issue doesn’t make a lot of sense. Please create a new issue and attach a screenshot showing the issue.

**Comment by sosauce** [comment]
Forgot what I said, I fixed it by guving a custom HazeStyle
