### ISSUE TITLE
Crash when using 2+ nested HazeState

### ISSUE THREAD

**Issue by Plovotok** [chrisbanes/haze#443]
## Information

  - Haze version: 1.1.1
  - Platform: Android
  - Platform version: [Android 12+]

## Actual Behavior
Crash with stack trace:
```
java.lang.IllegalStateException: Recording currently in progress - missing #endRecording() call?
at android.graphics.RenderNode.beginRecording(RenderNode.java:484)
at android.graphics.RenderNode.beginRecording(RenderNode.java:503)
...
```

## Steps to Reproduce the Problem
```
   val hazeState = remember {
        HazeState()
    }
    Scaffold(
        bottomBar = {
            Box(modifier = Modifier
                .fillMaxWidth()
                .height(80.dp)
                .hazeChild(hazeState)
            )
        }
    ) { paddings ->
        Box(modifier = Modifier.fillMaxSize().haze(hazeState)) {

            val contentHazeState = remember {
                HazeState()
            }

            Box(
                modifier = Modifier.fillMaxSize(),
                contentAlignment = Alignment.Center
            ) {

                val items = remember {
                    listOf(
                        "Item 1",
                        "Item 2",
                        "Item 3",
                        "Item 4",
                        "Item 5",
                    )
                }

                Box(
                    modifier = Modifier.fillMaxSize().haze(contentHazeState)
                ) {
                    LazyRow {
                        items(items) {
                            val itemHaze = remember {
                                HazeState()
                            }
                            Box(modifier = Modifier.size(76.dp)) {
                                Text(text = it)
                                IconButton(
                                    onClick = {},
                                    modifier = Modifier.hazeChild(itemHaze)
                                ) {
                                    Icon(
                                        imageVector = Icons.Default.MoreHoriz,
                                        contentDescription = null
                                    )
                                }
                            }
                        }
                    }
                }
            }

            Box(modifier = Modifier.fillMaxWidth().height(70.dp).hazeChild(contentHazeState))
        }
    }
```

**Comment by chrisbanes** [comment]
Yes, currently expected.

I don't know what your use case is, but being able to have nested blurring is being worked on in #441

**Comment by Plovotok** [comment]
Thx!)

**Comment by sosauce** [comment]
Hello @Plovotok ! What did you end up doing for nested blurring ?

**Comment by chrisbanes** [comment]
FYI: I'll be releasing 1.2.0 probably tomorrow with this. You can try the snapshot now if you'd like.
